In [1]:
import numpy

In [3]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

In [4]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [14]:
type(array1)

# ndarray는 n-demention array 라는 뜻임

numpy.ndarray

In [9]:
array1.shape

(11,)

In [15]:
# 이런걸 2차원 Array라고 부름
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
array2.shape
# (3, 4) 임 (세로 / 가로)

(3, 4)

In [23]:
# numpy array 에 총 몇개의 element 가 있나!
array1.size

11

In [25]:
array2.size # 4개씩 3개 12맞음

12

In [27]:
# 균일한 값으로 생성하기
array3 = numpy.full(6,7) # 7로 6개를 채움..

In [28]:
array3

array([7, 7, 7, 7, 7, 7])

In [44]:
# 모든 값이 0인 numpy array 생성하기
# numpy.zeros 가 훨씬 빠르다고 함..
# ref: https://stackoverflow.com/questions/26213199/np-fullsize-0-vs-np-zerossize-vs-np-empty
filled_by_six = numpy.zeros(6, dtype=int)

In [45]:
filled_by_six

array([0, 0, 0, 0, 0, 0])

In [46]:
# 모든 값이 1인 numpy array 생성하기

In [47]:
filled_by_one = numpy.ones(6, dtype=int)

In [48]:
filled_by_one

array([1, 1, 1, 1, 1, 1])

In [53]:
# 랜덤 값 생성하기
filled_by_random = numpy.random.random(6)

In [54]:
filled_by_random

array([0.14583998, 0.29939876, 0.11704173, 0.58455518, 0.05931898,
       0.68791718])

In [55]:
# 연속된 값이 담긴 numpy array 만들기
continuously_value_parameter_one = numpy.arange(6)

In [57]:
# 이러면 차례대로 0부터 만들어진다!!
continuously_value_parameter_one

array([0, 1, 2, 3, 4, 5])

In [60]:
# 파라미터를 2개를 넣으면... n 부터 m-1까지의 값들이 담긴 numpy array가 리턴됨
continously_value_parameter_two = numpy.arange(2, 7)

In [61]:
continously_value_parameter_two

array([2, 3, 4, 5, 6])

In [64]:
# 파라미터 3개를 넣으면, 이전 2개에 간격이 추가됨
continously_value_parameter_three = numpy.arange(2,20,2)

In [65]:
continously_value_parameter_three

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])