In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [4]:
# 파이썬의 리스트처럼 인덱스를 통해 배열 불러오기가 가능함..

array1[0]

2

In [5]:
array1[2]

5

In [7]:
# 개별 element에 assign 할 수 있다...
array1[-1]

31

In [9]:
# 그럼 .. list slice도 지원하나..??
array1[:-2] # 29,31 안나와야...

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [15]:
array1[[1,3,4]] # 이렇게 하면 .. 특정원소들의 집합만 꺼낼 수 있다..

array([ 3,  7, 11])

In [16]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [17]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [18]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [21]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

### Numpy 기본연산

In [22]:
import numpy as np

In [23]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [24]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### 모든 원소에 2를 곱하기

##### 상식적인 방법

In [26]:
for i in range(len(array1)):
    array1[i] = array1[i] * 2

In [27]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Numpy에선...

In [28]:
array1 = np.arange(10)

In [30]:
array1 * 2 # !!!! 이렇게 된다...

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 배열끼리의 연산

arr1과 arr2의 element를 같이 더하려면 고민 좀 해야됨..  
그러나 여기선...

In [32]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
array1 + array2 # 미침...;

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

덧셈 말고 당연 곱셈도 됨...

In [35]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

그럼, 나눗셈도 가능함..

In [39]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [43]:
# 혹시 이런것도 되나....

array1 // array2 # 된다........

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Boolean 도 가능함 ~~(미침...)~~

In [49]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [50]:
array1 > 4 # 4보다 큰 값만 True

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
array1 % 2 == 0 # 짝수만

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [52]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

**현재는 2, 5, 9 만 False로 되어있음**

In [58]:
np.where(booleans) # True 반환?

(array([ 0,  1,  3,  4,  6,  7,  8, 10]),)

In [59]:
np.where(booleans == False)

(array([2, 5, 9]),)

In [62]:
np.where(array1 > 4) # 0, 1 인덱스만 제외하고 인덱스 반환함

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [63]:
Filter = np.where(array1 > 4)

In [64]:
Filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [67]:
array1[Filter] # 이렇게 하면 0,1 인덱스 제외한 값이 튀어나옴..

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

### numpy vs list
Numpy가 훨씬 빠름.  
(이유는 list 는 수치 이외의 것도 다 들어감..)

### 최댓값, 최솟값, 평균값, 중앙값, 표준편차, 분산..

In [74]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

#최댓값 구하기
print("array1의 최댓값: ", array1.max())

#최솟값
print("array1의 최솟값: ", array1.min())

#평균값
print("array1의 평균값: ", array1.mean())

#중간값
print("array1의 중간값: ", np.median(array1))

#표준편차
print("array1의 표준편차: ", array1.std())

#분산
print("array1의 분산: ", array1.var())

array1의 최댓값:  31
array1의 최솟값:  5
array1의 평균값:  15.25
array1의 중간값:  13.5
array1의 표준편차:  8.496322733983215
array1의 분산:  72.1875
